# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: henry2004y/Batsrus.jl
          path: my-tools

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      # Cannot directly clone a public repo!
      - name: Clone GitHub repository
        run: git clone git@github.com:henry2004y/Batsrus.jl
        continue-on-error: true
      
      - name: Clone GitLab repository
        run: git clone git@gitlab.com:gitlab-examples/ruby-function
        continue-on-error: true

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Julia
        run: |
           julia -v
           julia -e 'println("Hello from Julia!")'
           julia -e 'using Pkg; Pkg.install("Vlasiator")'
        continue-on-error: true
        
      - name: GCC
        run: |
           which gcc
           gcc --version
           sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
           gcc --version
           
      - name: MPI
        run: |
           mpicc --version
        continue-on-error: true
        
      - name: Boost
        run: dpkg -s libboost-dev | grep 'Version'


